### ISSUE TITLE
A small amount of users bypass spam rules

### ISSUE THREAD

**Issue by QWERTYman2020** [japaneseenrichmentorganization/Yuno-Gasai-2#6]
a small subset of users bypass the custom spamrules and can not use XP.
when a user of this subset tries to use XP or violates the spam rules, Yuno throws "cannot get [property] of null" on a line where message.member.[property] is called.

**Comment by blubskye** [comment]
Issue fixed with: https://github.com/japaneseenrichmentorganization/Yuno-Gasai-2/pull/9/commits/9967df31aa82ca2ef7a8b972ec682ef892bbb9fc
